export const Categories = [
  { category: "Housing", label: "Housing", color: "#FF6347" },
  { category: "Utilities", label: "Utilities", color: "#4682B4" },
  { category: "Food_and_Dining", label: "Food and Dining", color: "#FFD700" },
  { category: "Insurance", label: "Insurance", color: "#FF1493" },
  { category: "Healthcare", label: "Healthcare", color: "#8A2BE2" },
  { category: "Education", label: "Education", color: "#3CB371" },
  { category: "Grocery", label: "Groceries", color: "#DC143A" },
  {
    category: "Subscription",
    label: "Subscriptions & Memberships",
    color: "#6A5ACD",
  },
  { category: "Debt_Payment", label: "Debt Payments", color: "#A52A2A" },
  {
    category: "Health_and_Fitness",
    label: "Health and Fitness",
    color: "#00CED1",
  },
  { category: "Office_expenses", label: "Office Expenses", color: "#D2691E" },
  { category: "Shopping", label: "Shopping", color: "#DC143C" },
  { category: "Entertainment", label: "Entertainment", color: "#FF8C00" },
  { category: "Transportation", label: "Transportation", color: "#32CD32" },
  { category: "Personal_Care", label: "Personal Care", color: "#FFB6C1" },
  { category: "Other_Transfers", label: "Other Transfers", color: "#B0C4DE" },
  { category: "Other", label: "Other", color: "#8B4513" },
];
